services:
  - type: web
    name: hospital-app
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    packages:
      - unixodbc
      - unixodbc-dev
      - msodbcsql17
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app 
    packages:
      - unixodbc
      - unixodbc-dev
